<?php

/**
 * @file
 *   BugHerd module functions.
 */

use Drupal\Component\Utility\String;

/**
 * Implements hook_page_build().
 */
function bugherd_page_build(&$page) {

  if (!\Drupal::currentUser()->hasPermission('access bugherd'))
    return;

  $disable_on_admin = \Drupal::config('bugherd.settings')->get('disable_on_admin', FALSE);
  if (\Drupal::service('router.admin_context')->isAdminRoute(\Drupal::routeMatch()->getRouteObject()) && $disable_on_admin) {
    return;
  }

  $api_key = \Drupal::config('bugherd.settings')->get('api_key', FALSE);
  if (!$api_key) {
    $link = \Drupal::l(t('Configure BugHerd'), new \Drupal\Core\Url('bugherd.settings'));
    drupal_set_message(t('BugHerd API key not set. !configure.',  array('!configure' => $link)), 'warning', FALSE);
    return;
  }

  $api_key = String::checkPlain($api_key);
  $script = <<<SCRIPT
  var _bugHerdAPIKey = '{$api_key}';
  (function (d, t) {
    var bh = d.createElement(t), s = d.getElementsByTagName(t)[0];
    bh.type = 'text/javascript';
    bh.src = '//www.bugherd.com/sidebarv2.js?apikey={$api_key}';
    s.parentNode.insertBefore(bh, s);
  })(document, 'script');

SCRIPT;

  $page['#attached']['js'][] = array(
    'type' => 'inline',
    'data' => $script,
    'scope' => 'footer',
    'every_page' => TRUE,
  );
}
