<?php

/**
 * @file
 *   BugHerd module functions.
 */

use Drupal\Component\Utility\SafeMarkup;

/**
 * Implements hook_page_attachments.
 */
function bugherd_page_attachments(&$page) {

  if (!\Drupal::currentUser()->hasPermission('access bugherd'))
    return;

  $disable_on_admin = \Drupal::config('bugherd.settings')->get('disable_on_admin', FALSE);
  if (\Drupal::service('router.admin_context')->isAdminRoute(\Drupal::routeMatch()->getRouteObject()) && $disable_on_admin) {
    return;
  }

  $api_key = \Drupal::config('bugherd.settings')->get('api_key', FALSE);
  if ($api_key === FALSE) {
    $link = \Drupal::l(t('Configure BugHerd'), new \Drupal\Core\Url('bugherd.settings'));
    drupal_set_message(t('BugHerd API key not set. @configure.',  array('@configure' => $link)), 'warning', FALSE);
    return;
  }

  $api_key = SafeMarkup::checkPlain($api_key);
  $page['#attached']['library'][] = 'bugherd/snippet';
  $page['#attached']['drupalSettings']['bugherd']['snippet']['key'] = $api_key;
}
